### PR TITLE
Tests improvements

### PR DESCRIPTION
**Pull request by duck-rh**

### CODE REVIEW

**Comment by StykMartin** [comment]
🤔 No review here

**Comment by duck-rh** [comment]
@StykMartin I don't know who to ask for review at the moment and I did not want to bother you. Now I'm always open to comments.

**Comment by StykMartin** [comment]
I can always review 🤔👀

**Comment by duck-rh** [comment]
@StykMartin OK, thanks :-). I contacted Petr and following his advice contacted Carol, so I hope we can have a small team of reviewers.

**Pull request merged**
