### PR TITLE
Update developers information

### PR DESCRIPTION
**Pull request by renanrodrigo**

### CODE REVIEW

**Review by famousgarkin — APPROVED** [review]

**Review by duck-rh — APPROVED** [review]
I have no idea how your team evolves but the changes are technically sound.

The tests fail for another reason and I made another PR to fix that: https://github.com/beaker-project/beaker-infrastructure/pull/28

**Review by StykMartin — APPROVED** [review]
🤔

**Comment by StykMartin** [comment]
Why no merge @duck-rh?

**Comment by duck-rh** [comment]
> Why no merge @duck-rh?

I was told to wait for reviews by someone you know ;-P

**Comment by StykMartin** [comment]
> > Why no merge @duck-rh?
> 
> I was told to wait for reviews by someone you know ;-P

I see good changes I merge :| I'm a simple man.

**Pull request merged**
