### PR TITLE
Off board Martin

### PR DESCRIPTION
**Pull request by StykMartin**
Martin is dead, long live to 🤔 ?

### CODE REVIEW

**Comment by renanrodrigo** [comment]
lol linters

**Comment by StykMartin** [comment]
Looks like something new.
@duck-rh can you fix it (in separate PR).

**Review by renanrodrigo — APPROVED** [review]
Sadly approved.

**Comment by StykMartin** [comment]
> Sadly approved.

Next time you better approve it with a smile on the face :eyes: 🐬

**Comment by duck-rh** [comment]
@StykMartin see you around.

There's changes in ansible-lint, I'm going to fix the playbooks to let this in. I'm already working on the roles too but that does not seem to affect the tests.

**Comment by duck-rh** [comment]
> @StykMartin see you around.
> 
> There's changes in ansible-lint, I'm going to fix the playbooks to let this in. I'm already working on the roles too but that does not seem to affect the tests.

Please review #25

**Pull request merged**
