### PR TITLE
Add new Beaker god into list

### PR DESCRIPTION
**Pull request by StykMartin**
Welcome @danrodrig! :tada: :tada: :tada: 
Signed-off-by: Martin Styk <mastyk@redhat.com>

### CODE REVIEW

**Comment by renanrodrigo** [comment]
welcome
there will be cake

**Comment by StykMartin** [comment]
@duck-rh are you with us?

**Review by renanrodrigo — APPROVED** [review]
LGTM

**Comment by duck-rh** [comment]
@StykMartin sorry, I was eating good cheese in France at the time, but I'm back \\_o<

**Pull request merged**
